[package]
name = "hcache-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
procfs = "0.18"
libc = "0.2.177"
serde = {version = "1.0.219",features = ["derive"]}
chrono = "0.4.41"
